# Generated by Django 4.2.7 on 2023-11-14 02:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="news/")),
                ("description", models.TextField()),
                ("content", ckeditor.fields.RichTextField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("twitter_link", models.URLField()),
                ("facebook_link", models.URLField()),
                ("telegram_link", models.URLField()),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
